# Generated by Django 4.1.7 on 2023-03-16 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_vote', models.CharField(choices=[('34', '202102872'), ('33', '202102667'), ('32', '202102368'), ('31', '202102118'), ('30', '202101559'), ('29', '202101343'), ('28', '202100923'), ('27', '202100923-2'), ('26', '202100805'), ('25', '202100694'), ('24', '202003371'), ('23', '202002522'), ('22', '202002238'), ('21', '202002134'), ('20', '202001054'), ('19', '202001022'), ('18', '201904507'), ('17', '201903915'), ('16', '201903542'), ('15', '201903421'), ('14', '201903228'), ('13', '201902637'), ('12', '201902619'), ('11', '201902332'), ('10', '201901960'), ('9', '201901667'), ('8', '201900473'), ('7', '201803952'), ('6', '201803760'), ('5', '201802848'), ('4', '201800951'), ('3', '201800628'), ('2', '201800306'), ('1', '201701072')], max_length=5, null=True, verbose_name='투표번호')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='아이디')),
            ],
            options={
                'verbose_name': '투표이미지',
                'verbose_name_plural': '투표이미지',
                'db_table': 'PIMAGE_TB',
            },
        ),
    ]
